server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctors/**

        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**

        - id: availability-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/availability/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/